name: Varbase Admin Base
description: A recipe to manage default installed modules, configs and permissions for Varbase admin experience.
type: Varbase Admin
install:
  - node
  - gin
  - roleassign
  - config_perms
  - admin_audit_trail
  - admin_audit_trail_file
  - admin_audit_trail_media
  - admin_audit_trail_user
  - admin_audit_trail_taxonomy
  - admin_audit_trail_node
  - admin_audit_trail_menu
  - admin_audit_trail_auth
  - masquerade
  - menu_admin_per_menu
  - revision_log_default
  - syslog
  - update
  - autosave_form
  - settings_tray
  - entity_clone
  - taxonomy_manager
  - taxonomy_access_fix
  - coffee
  - length_indicator
  - navigation
  - navigation_extra_tools
  - gin_toolbar
  - gin_login
  - gin_everywhere
  - gin_type_tray
  - trash
  - eca_vbo
  - ui_icons
config:
  import:
    autosave_form:
      - autosave_form.messages
    navigation:
      - navigation.settings
      - system.menu.content
  actions:
    user.settings:
      simpleConfigUpdate:
        register: admin_only
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    gin.settings:
      simpleConfigUpdate:
        logo:
          path: profiles/contrib/varbase/images/varbase-medium-logo-emblem-color.png
          use_default: false
        favicon:
          mimetype: image/vnd.microsoft.icon
          path: profiles/contrib/varbase/images/favicon.ico
          use_default: false
        show_description_toggle: true
    gin_login.settings:
      simpleConfigUpdate:
        logo:
          use_default: false
          path: themes/contrib/vartheme_bs5/logo.svg
        brand_image:
          use_default: true
    navigation.settings:
      simpleConfigUpdate:
        logo:
          provider: custom
          path: profiles/contrib/varbase/images/varbase-medium-logo-emblem-color.png
          max:
            filesize: 1048576
            height: 40
            width: 40
    user.role.authenticated:
      grantPermissions:
        - 'access navigation'
        - 'access toolbar'
